name: Build and Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate site
      run: python generate_html.py

    - name: Deploy to VPS via rsync
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519" ./out/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/
        rsync -avz -e "ssh -i ~/.ssh/id_ed25519" ./www/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/
