name: Build and Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate site
      run: python generate_html.py

    # - name: Debug SSH command
    #   run: |
    #     echo "ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}"

    # - name: Deploy manually with rsync
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
    #     chmod 600 ~/.ssh/id_ed25519
    #     ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH OK'"
    #     rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" ./out/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/

    - name: Deploy with base64-decoded key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_DEPLOY_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo SSH OK"
        rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519" ./out/ ./www/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/html/


